# Generated by Django 5.2.14 on 2026-06-10 06:24

import django.core.files.storage
import sss.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0038_accessgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='legend_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/gokart-sss-django/private-media'), upload_to=sss.models.legend_upload_path),
        ),
    ]
